### ISSUE TITLE
Live playback offset by -2 hours

### ISSUE THREAD

**Issue by Chivs** [plexinc-plugins/BBC-iPlayer.bundle#30]
Playing Live streams on the server works fine, however playing live TV on the Roku box is offset by two hours in the past. Seems like the Roku is playing Live TV from the earliest point in the stream rather than the end. It's not always 100% consistent however, occasionally it will play Live TV correctly, but this is rare.
Example: Watching BBC News at 17:00 UK time plays the news from 15:00

**Comment by meriko** [comment]
@Chivs 
The live streams from BBC are provided like this to support restart of programs. Other clients will start playback at the latest available segment, so I suppose it's a specific Roku client problem? See second post in this thread: http://forums.roku.com/viewtopic.php?p=427008&sid=c68a62536b439330ece8c14b390234f7

**Comment by meriko** [comment]
@Chivs 
Fixed in Roku client >= 4.1.14
