### ISSUE TITLE
top level highlights and most popular   no longer scrape

### ISSUE THREAD

**Issue by eetjtl** [plexinc-plugins/BBC-iPlayer.bundle#51]
The code for top level "highlights" and "most popular" needs reworked as the pages changed.

in the "most popular" can probably reuse some code as it is similar to other pages now. 

Thanks
ps I will play around with it and see if I can get it. Before you have a chance to look at it.

**Comment by meriko** [comment]
Fixed in https://github.com/plexinc-plugins/BBC-iPlayer.bundle/pull/52

I haven't completely gone through the site changes, so episode numbers etc might not show up correctly but at least the videos will now list

**Comment by eetjtl** [comment]
thanks for the fix
