### ISSUE TITLE
live tv  pulls up no data

### ISSUE THREAD

**Issue by eetjtl** [plexinc-plugins/BBC-iPlayer.bundle#53]
they changed the webpage so the servicecode xpath needs changed to pull in "title" , etc.
Right now it never attempts the for statement as xpath returns nothing  (the rest of the code has except statements to counter xpath issues) thus no VideoClipObject is created.

**Comment by shopgirl284** [comment]
According to the user it sounds like the BBC iplayer website also requires users to sign in to play live streams now. If that is the case, then live streams will no longer work, since the plugin does not provide a method to authenticate users.

**Comment by sander1** [comment]
Metadata fixed with https://github.com/plexinc-plugins/BBC-iPlayer.bundle/commit/551b765f383356da376aa8ac36b33b35d97ea276
