### ISSUE TITLE
API still not working correctly for iplayer plugin

### ISSUE THREAD

**Issue by tropas2001** [plexinc-plugins/BBC-iPlayer.bundle#56]
I raised the issue https://github.com/plexinc-plugins/BBC-iPlayer.bundle/issues/55 and whilst I can confirm after the upgrade I no longer see errors in my logs, the API isn't listing that iplayer as playing anything;

http://<plexserver>:32400/status/sessions?X-Plex-Token=XXXXXXXXXXXXX

**Comment by tropas2001** [comment]
I've taken a packet capture between my plex remote on an iphone and a rasplex device. when I press the play button two commands are sent....

GET /player/playback/playMedia?address=XX-XX-XX-XX.XXXXXXXX.plex.direct&commandID=106&containerKey=%2Fvideo%2Fiplayer%2Fliveradio%3Ftitle%3DLive%2BRadio&key=%2Fvideo%2Fiplayer%2FCreatePlayableObject%3Fart%3Dhttp%253A%252F%252Fstatic.bbci.co.uk%252Fradio%252F690%252F1.39%252Fimg%252Fbackgrounds%252Fservices%252Fbbc_radio_two_t1.jpg%26thumb%3D%252F%253A%252Fplugins%252Fcom.plexapp.plugins.iplayer%252Fresources%252Fbbc_radio_two.png%253Ft%253D1519221692%26title%3DBBC%2BRadio%2B2%26url%3Dhttp%253A%252F%252Fopen.live.bbc.co.uk%252Fmediaselector%252F5%252Fselect%252Fversion%252F2.0%252Fformat%252Fjson%252Fmediaset%252Fapple-ipad-hls%252Fvpid%252Fbbc_radio_two%26include_container%3D1%26type%3Dhls&machineIdentifier=XXXXXXXXXXX&offset=0&port=32400&protocol=https&token=transient-XXXXXXX-XXXX-XXXX-80e9-c936c7fc3a4a&type=music&X-Plex-Device-Name=Andy%E2%80%99s%20iPhone%20%284%29

Returns: 

```
HTTP/1.1 200 OK
...
<Response code="500" status="Could not find that item" />
```

and then
GET /player/playback/play?commandID=48&type=music&X-Plex-Device-Name=Andy%E2%80%99s%20iPhone%20%284%29 HTTP/1.1

returns
<Response code="200" status="OK" />

...and then the music plays.

**Comment by sander1** [comment]
I'm still 99.9% sure that PMS has never reported playbacks from channels.....

**Comment by sander1** [comment]
And even if it ever did, it's still not a channel issue.
